### PR TITLE
Html refactor

### PR DESCRIPTION
**Pull request by SeanCramsey**
This should work, though i changed a lot of stuff so it might all explode.
Alot of the css may need to be changed for a "final display," adjusting heights and widths, converting to percent values, etc.

### CODE REVIEW

**Comment by SeanCramsey** [comment]
line 386; size()-1 might have to be length -1, im not sure

**Comment by wwang126** [comment]
This line right [here](https://github.com/cs361fall2017/team8/blob/f20ff548b4d83ea780a0c4a4c18ad61d5b5166dd/src/main/java/views/AcesUp/AcesUp.flt.html#L106) needs to get changed to match with [this](    $.each(game.cols[0].cards, function( key, val ) {)

**Comment by wwang126** [comment]
The cards show up now. But I'm not sure if the drag and drop works.

**Comment by wwang126** [comment]
Just tested it out, works fine for me.

**Pull request merged**
